"""empty message

Revision ID: 2c953ea402ca
Revises: e3ae51a0b5a9
Create Date: 2023-09-02 01:58:00.637717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c953ea402ca'
down_revision = 'e3ae51a0b5a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('platform', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'platform')
    # ### end Alembic commands ###
