"""empty message

Revision ID: 55fd8b52ff58
Revises: b2060fffa8ad
Create Date: 2023-11-04 18:17:16.886891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55fd8b52ff58'
down_revision = 'b2060fffa8ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='password_reset_token_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='password_reset_token_pkey'),
    sa.UniqueConstraint('token', name='password_reset_token_token_key')
    )
    # ### end Alembic commands ###
