"""empty message

Revision ID: 6c18aa8572d0
Revises: e4b8ea45c525
Create Date: 2023-11-04 06:21:29.416318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c18aa8572d0'
down_revision = 'e4b8ea45c525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset', sa.Column('expiry', sa.DateTime(), nullable=False))
    op.drop_column('password_reset', 'expires_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('password_reset', 'expiry')
    # ### end Alembic commands ###
